import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#1B1B2A',
  panel: '#24243A',
  panelAlt: '#2D2D46',
  surface: '#151522',
  line: '#454561',
  text: '#FFFFFF',
  muted: '#AAAAC4',
  pink: '#FF007A',
  mint: '#00FFB3',
  purple: '#A700FF',
  yellow: '#FFEA00',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.ink },
  app: { flex: 1, backgroundColor: colors.ink, ...(Platform.OS === 'web' ? { width: '100%', maxWidth: 720, alignSelf: 'center' as const, minHeight: 0 } : {}) },
  background: { bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0 },
  bgLineOne: { backgroundColor: colors.pink, height: 860, left: 34, opacity: 0.08, position: 'absolute', top: -150, transform: [{ rotate: '22deg' }], width: 4 },
  bgLineTwo: { backgroundColor: colors.mint, height: 720, opacity: 0.07, position: 'absolute', right: 78, top: 20, transform: [{ rotate: '-18deg' }], width: 4 },
  bgLineThree: { backgroundColor: colors.purple, height: 560, opacity: 0.1, position: 'absolute', right: 18, top: 230, transform: [{ rotate: '38deg' }], width: 5 },
  header: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 10 },
  logoFrame: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 12, borderWidth: 1, height: 54, overflow: 'hidden', width: 54 },
  logo: { height: '100%', width: '100%' },
  headerText: { flex: 1 },
  title: { color: colors.text, fontSize: 30, fontWeight: '900', lineHeight: 34 },
  badge: { alignItems: 'center', backgroundColor: 'transparent', minWidth: 54, paddingVertical: 7 },
  badgeValue: { color: colors.yellow, fontSize: 20, fontWeight: '900' },
  badgeLabel: { color: colors.mint, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  headerClock: { alignItems: 'center', backgroundColor: '#00FFB312', borderColor: colors.mint, borderRadius: 10, borderWidth: 1, minWidth: 86, paddingHorizontal: 10, paddingVertical: 7 },
  headerClockText: { color: colors.mint, fontSize: 18, fontWeight: '900', marginTop: 2 },
  content: { paddingHorizontal: 18, paddingBottom: 106 },
  screen: { gap: 16 },
  hero: { backgroundColor: colors.panel, borderColor: colors.purple, borderLeftColor: colors.pink, borderLeftWidth: 4, borderRadius: 14, borderWidth: 1, elevation: 4, overflow: 'hidden', padding: 18, position: 'relative', shadowColor: colors.pink, shadowOffset: { height: 6, width: 0 }, shadowOpacity: 0.14, shadowRadius: 14 },
  heroGlow: { backgroundColor: colors.pink, height: 150, opacity: 0.1, position: 'absolute', right: -45, top: -45, transform: [{ rotate: '-22deg' }], width: 220 },
  eyebrow: { color: colors.mint, fontSize: 12, fontWeight: '900', letterSpacing: 0.8, textTransform: 'uppercase' },
  heroTitle: { color: colors.text, fontSize: 42, fontWeight: '900', lineHeight: 46, marginTop: 4 },
  heroSub: { color: colors.muted, fontSize: 15, marginTop: 2 },
  quickStats: { flexDirection: 'row', gap: 8, marginTop: 16 },
  stat: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 1, flex: 1, minHeight: 58, justifyContent: 'center', paddingHorizontal: 9 },
  statValue: { color: colors.yellow, fontSize: 16, fontWeight: '900' },
  statLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 2, textTransform: 'uppercase' },
  primaryWide: { alignItems: 'center', backgroundColor: colors.pink, borderRadius: 10, justifyContent: 'center', marginTop: 16, minHeight: 50 },
  resumeWide: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 10, justifyContent: 'center', marginTop: 16, minHeight: 50 },
  primaryText: { color: colors.ink, fontSize: 14, fontWeight: '900' },
  secondaryFull: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 2, justifyContent: 'center', marginTop: 12, minHeight: 46 },
  secondaryText: { color: colors.text, fontSize: 14, fontWeight: '900', textTransform: 'uppercase' },
  dangerOutlineFull: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.pink, borderRadius: 10, borderWidth: 1, justifyContent: 'center', marginTop: 12, minHeight: 44 },
  dangerOutlineText: { color: colors.pink, fontSize: 13, fontWeight: '900', textTransform: 'uppercase' },
  smallButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.mint, borderRadius: 9, borderWidth: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 12 },
  disabledButton: { borderColor: colors.line, opacity: 0.35 },
  smallButtonText: { color: colors.text, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  backButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 9, borderWidth: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 12 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 },
  chipActive: { backgroundColor: colors.purple, borderColor: colors.yellow },
  chipText: { color: colors.text, fontSize: 13, fontWeight: '900' },
  card: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  cardTitle: { color: colors.text, fontSize: 20, fontWeight: '900' },
  textInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 6, minHeight: 44, paddingHorizontal: 10 },
  compactText: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 12 },
  exerciseList: { gap: 8, marginTop: 14 },
  exerciseBlock: { gap: 8 },
  exerciseRow: { alignItems: 'center', backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 64, padding: 10 },
  exerciseNumber: { alignItems: 'center', backgroundColor: colors.purple, borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  exerciseNumberText: { color: colors.yellow, fontWeight: '900' },
  exerciseBody: { flex: 1 },
  rowTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  rowMuted: { color: colors.muted, fontSize: 12, marginTop: 3 },
  rowValue: { color: colors.mint, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  planEditor: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 1, gap: 8, padding: 8 },
  stepperRow: { flexDirection: 'row', gap: 8 },
  editorActions: { flexDirection: 'row', gap: 8 },
  templateActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  templateSecondaryAction: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 2, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 10 },
  templatePrimaryAction: { alignItems: 'center', backgroundColor: colors.pink, borderColor: colors.pink, borderRadius: 10, borderWidth: 2, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 10 },
  quickStartList: { gap: 8, marginTop: 12 },
  quickStartRow: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 58, padding: 10 },
  quickStartButton: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 8, justifyContent: 'center', minHeight: 38, minWidth: 72, paddingHorizontal: 12 },
  quickStartButtonText: { color: colors.ink, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  planQuickCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  planQuickActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  planEditButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 9, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 42 },
  planStartButton: { alignItems: 'center', backgroundColor: colors.pink, borderRadius: 9, flex: 1.4, justifyContent: 'center', minHeight: 42 },
  reorderButton: { alignItems: 'center', borderColor: colors.purple, borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  reorderText: { color: colors.text, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  removeButton: { alignItems: 'center', borderColor: colors.pink, borderRadius: 8, borderWidth: 1, flex: 1.2, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  removeButtonText: { color: colors.muted, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  stepper: { flex: 1, gap: 5, minWidth: 0 },
  stepperLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  stepperControls: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 9, borderWidth: 1, flexDirection: 'row', minHeight: 42, overflow: 'hidden' },
  stepperButton: { alignItems: 'center', alignSelf: 'stretch', justifyContent: 'center', width: 34 },
  stepperButtonText: { color: colors.yellow, fontSize: 18, fontWeight: '900' },
  stepperValue: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '900', textAlign: 'center' },
  libraryDetailCard: { backgroundColor: colors.panel, borderColor: colors.purple, borderRadius: 12, borderWidth: 1, gap: 12, padding: 14 },
  libraryHeroTop: { flexDirection: 'row', gap: 12 },
  metaPillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 },
  metaPill: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 999, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 6 },
  metaPillText: { color: colors.mint, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  libraryList: { gap: 8 },
  progressChartCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  progressBars: { alignItems: 'flex-end', flexDirection: 'row', gap: 4, height: 104, marginVertical: 14 },
  progressBarColumn: { flex: 1, height: 96, justifyContent: 'flex-end' },
  progressBar: { borderRadius: 4, minHeight: 4, width: '100%' },
  progressBarPink: { backgroundColor: colors.pink },
  progressBarMint: { backgroundColor: colors.mint },
  progressBarYellow: { backgroundColor: colors.yellow },
  progressHistoryList: { gap: 4, marginTop: 10 },
  progressHistoryRow: { alignItems: 'center', borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10 },
  libraryRow: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 54, padding: 12 },
  libraryRowActive: { backgroundColor: colors.panelAlt, borderColor: colors.mint, borderWidth: 2 },
  exerciseDetailTitle: { flex: 1, gap: 4 },
  descriptionBox: { backgroundColor: colors.panelAlt, borderColor: colors.purple, borderRadius: 10, borderWidth: 1, marginTop: 14, padding: 14 },
  descriptionHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  descriptionLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  descriptionText: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 8 },
  noteInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 14, lineHeight: 20, marginTop: 12, minHeight: 74, padding: 10, textAlignVertical: 'top' },
  workoutSetTypeRow: { marginBottom: 14, marginTop: 8 },
  workoutRestActions: { marginTop: 14 },
  workoutNoteLabel: { marginTop: 14 },
  workoutTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  compactWorkoutHeader: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.purple, borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 14 },
  restEditingHint: { alignItems: 'center', backgroundColor: '#00FFB312', borderColor: colors.mint, borderRadius: 9, borderWidth: 1, minHeight: 38, justifyContent: 'center', paddingHorizontal: 10 },
  restEditingHintText: { color: colors.mint, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  setTableCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, overflow: 'hidden' },
  setTableHeader: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.purple, borderBottomWidth: 1, flexDirection: 'row', minHeight: 36, paddingHorizontal: 8 },
  setHeaderText: { color: colors.muted, fontSize: 9, fontWeight: '900', textAlign: 'center', textTransform: 'uppercase' },
  setTableRow: { alignItems: 'center', borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', minHeight: 58, paddingHorizontal: 8 },
  setTableRowActive: { backgroundColor: '#A700FF18', borderLeftColor: colors.yellow, borderLeftWidth: 3 },
  setNumberCell: { alignItems: 'center', justifyContent: 'center', width: 38 },
  setPreviousCell: { flex: 1.15, minWidth: 0 },
  setMetricCell: { alignItems: 'center', flex: 1, justifyContent: 'center', minWidth: 0, paddingHorizontal: 3 },
  setDoneCell: { alignItems: 'center', justifyContent: 'center', width: 48 },
  setNumberText: { color: colors.yellow, fontSize: 14, fontWeight: '900' },
  setPreviousText: { color: colors.muted, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  setMetricInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 7, borderWidth: 1, color: colors.text, fontSize: 14, fontWeight: '900', minHeight: 38, paddingHorizontal: 4, paddingVertical: 6, textAlign: 'center', width: '100%' },
  setDoneButton: { alignItems: 'center', backgroundColor: colors.pink, borderRadius: 8, height: 38, justifyContent: 'center', width: 38 },
  setDoneButtonText: { color: colors.ink, fontSize: 18, fontWeight: '900' },
  setDoneComplete: { alignItems: 'center', backgroundColor: colors.mint, borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  setDoneCompleteText: { color: colors.ink, fontSize: 17, fontWeight: '900' },
  setDonePending: { borderColor: colors.line, borderRadius: 8, borderWidth: 1, height: 32, width: 32 },
  addSetInline: { alignItems: 'center', justifyContent: 'center', minHeight: 44 },
  addSetInlineText: { color: colors.mint, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  moreButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 1, justifyContent: 'center', minHeight: 44 },
  compactNoteInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 13, marginTop: 10, minHeight: 48, padding: 10, textAlignVertical: 'top' },
  timerCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.purple, borderRadius: 14, borderWidth: 1, padding: 18 },
  timerCircle: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.mint, borderRadius: 150, borderWidth: 4, elevation: 5, height: 260, justifyContent: 'center', marginVertical: 18, shadowColor: colors.mint, shadowOffset: { height: 0, width: 0 }, shadowOpacity: 0.2, shadowRadius: 14, width: 260 },
  timerMain: { color: colors.yellow, fontSize: 44, fontWeight: '700' },
  timerOvertime: { color: colors.pink },
  timerSub: { color: colors.muted, fontSize: 16, marginTop: 6 },
  contentWithRestDock: { paddingBottom: 142 },
  restDock: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.mint, borderRadius: 16, borderWidth: 1, bottom: 16, elevation: 12, flexDirection: 'row', gap: 10, left: 16, minHeight: 82, padding: 10, position: 'absolute', right: 16, shadowColor: colors.mint, shadowOffset: { height: 4, width: 0 }, shadowOpacity: 0.25, shadowRadius: 14 },
  restDockTimer: { alignItems: 'center', borderRightColor: colors.line, borderRightWidth: 1, justifyContent: 'center', minWidth: 64, paddingRight: 10 },
  restDockLabel: { color: colors.mint, fontSize: 9, fontWeight: '900', textTransform: 'uppercase' },
  restDockTime: { color: colors.yellow, fontSize: 25, fontWeight: '900', marginTop: 2 },
  restDockActions: { flex: 1, flexDirection: 'row', gap: 6 },
  restDockButton: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.purple, borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 44 },
  restDockButtonText: { color: colors.text, fontSize: 11, fontWeight: '900' },
  restDockSkip: { alignItems: 'center', backgroundColor: colors.pink, borderRadius: 8, flex: 1.15, justifyContent: 'center', minHeight: 44 },
  restDockSkipText: { color: colors.ink, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  toggle: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 5, padding: 4 },
  toggleItem: { alignItems: 'center', borderRadius: 4, flex: 1, minHeight: 34, justifyContent: 'center', paddingHorizontal: 10 },
  toggleActive: { backgroundColor: colors.yellow },
  toggleText: { color: colors.muted, fontSize: 12, fontWeight: '900' },
  toggleTextActive: { color: colors.ink, fontSize: 12, fontWeight: '900' },
  calendarMonth: { color: colors.yellow, fontSize: 26, fontWeight: '900' },
  calendarHint: { color: colors.muted, flex: 1, fontSize: 12, lineHeight: 16, textAlign: 'right' },
  weekHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  weekHeaderCenter: { alignItems: 'center', flex: 1 },
  iconButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  iconButtonText: { color: colors.mint, fontSize: 28, fontWeight: '600', lineHeight: 30 },
  weekSchedule: { flexDirection: 'row' },
  weekDayCard: { backgroundColor: colors.surface, borderBottomColor: colors.line, borderBottomWidth: 1, borderLeftColor: colors.line, borderLeftWidth: 1, borderTopColor: colors.line, borderTopWidth: 1, flex: 1, minHeight: 96, padding: 7 },
  weekDayFirst: { borderBottomLeftRadius: 8, borderTopLeftRadius: 8 },
  weekDayLast: { borderBottomRightRadius: 8, borderRightColor: colors.line, borderRightWidth: 1, borderTopRightRadius: 8 },
  calendarToday: { borderColor: colors.mint, borderRadius: 10, borderWidth: 2 },
  calendarSelected: { backgroundColor: colors.purple, borderColor: colors.yellow, borderRadius: 10, borderWidth: 2 },
  calendarWeekday: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  calendarNumber: { color: colors.text, fontSize: 15, fontWeight: '900' },
  calendarWorkoutDone: { color: colors.mint, fontSize: 13, fontWeight: '900', marginTop: 10 },
  calendarWorkoutEmpty: { color: colors.line, fontSize: 13, fontWeight: '900', marginTop: 10 },
  sectionTitle: { color: colors.pink, fontSize: 18, fontWeight: '900', letterSpacing: 0.7, textTransform: 'uppercase' },
  profileCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.purple, borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 14, padding: 14 },
  profileLogo: { borderRadius: 6, height: 82, width: 82 },
  historyLogCard: { backgroundColor: colors.panel, borderColor: colors.line, borderLeftColor: colors.mint, borderLeftWidth: 3, borderRadius: 12, borderWidth: 1, padding: 14 },
  tabBar: { backgroundColor: colors.surface, borderColor: colors.purple, borderRadius: 16, borderWidth: 1, bottom: 18, elevation: 8, flexDirection: 'row', gap: 5, left: 16, padding: 6, position: 'absolute', right: 16, shadowColor: colors.purple, shadowOffset: { height: 4, width: 0 }, shadowOpacity: 0.25, shadowRadius: 12 },
  tabButton: { alignItems: 'center', borderRadius: 10, flex: 1, minHeight: 42, justifyContent: 'center' },
  tabActive: { backgroundColor: colors.purple },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  tabTextActive: { color: colors.yellow },
});
