import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#08080A',
  panel: '#121216',
  panelAlt: '#18181D',
  line: '#2A2A32',
  text: '#F4F4F5',
  muted: '#A1A1AA',
  blue: '#D4D4D8',
  violet: '#3F3F46',
  red: '#E11D48',
  yellow: '#E5E7EB',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.ink },
  app: { flex: 1, backgroundColor: colors.ink },
  background: { bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0 },
  bgLineOne: { backgroundColor: '#27272A', height: 860, left: 34, opacity: 0.18, position: 'absolute', top: -150, transform: [{ rotate: '22deg' }], width: 2 },
  bgLineTwo: { backgroundColor: '#3F3F46', height: 720, opacity: 0.12, position: 'absolute', right: 78, top: 20, transform: [{ rotate: '-18deg' }], width: 2 },
  bgLineThree: { backgroundColor: '#18181B', height: 560, opacity: 0.18, position: 'absolute', right: 18, top: 230, transform: [{ rotate: '38deg' }], width: 3 },
  header: { alignItems: 'center', flexDirection: 'row', gap: 12, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 10 },
  logoFrame: { backgroundColor: 'transparent', borderRadius: 8, height: 54, overflow: 'hidden', width: 54 },
  logo: { height: '100%', width: '100%' },
  headerText: { flex: 1 },
  title: { color: colors.text, fontSize: 30, fontWeight: '900', lineHeight: 34 },
  badge: { alignItems: 'center', backgroundColor: 'transparent', minWidth: 54, paddingVertical: 7 },
  badgeValue: { color: colors.text, fontSize: 20, fontWeight: '900' },
  badgeLabel: { color: colors.text, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  headerClock: { alignItems: 'center', borderColor: colors.line, borderRadius: 6, borderWidth: 1, minWidth: 86, paddingHorizontal: 10, paddingVertical: 7 },
  headerClockText: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 2 },
  content: { paddingHorizontal: 18, paddingBottom: 106 },
  screen: { gap: 16 },
  hero: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, overflow: 'hidden', padding: 18, position: 'relative' },
  heroGlow: { backgroundColor: '#27272A', height: 150, opacity: 0.22, position: 'absolute', right: -45, top: -45, transform: [{ rotate: '-22deg' }], width: 220 },
  eyebrow: { color: colors.blue, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  heroTitle: { color: colors.text, fontSize: 42, fontWeight: '900', lineHeight: 46, marginTop: 4 },
  heroSub: { color: colors.muted, fontSize: 15, marginTop: 2 },
  quickStats: { flexDirection: 'row', gap: 8, marginTop: 16 },
  stat: { backgroundColor: '#13131F', borderColor: colors.line, borderRadius: 6, borderWidth: 1, flex: 1, minHeight: 54, justifyContent: 'center', paddingHorizontal: 9 },
  statValue: { color: colors.yellow, fontSize: 16, fontWeight: '900' },
  statLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 2, textTransform: 'uppercase' },
  primaryWide: { alignItems: 'center', backgroundColor: colors.red, borderRadius: 5, justifyContent: 'center', marginTop: 16, minHeight: 50 },
  resumeWide: { alignItems: 'center', backgroundColor: '#16A34A', borderRadius: 5, justifyContent: 'center', marginTop: 16, minHeight: 50 },
  primaryText: { color: '#fff', fontSize: 14, fontWeight: '900' },
  secondaryFull: { alignItems: 'center', backgroundColor: '#0B0B12', borderColor: colors.violet, borderRadius: 5, borderWidth: 2, justifyContent: 'center', marginTop: 12, minHeight: 46 },
  secondaryText: { color: colors.text, fontSize: 14, fontWeight: '900', textTransform: 'uppercase' },
  dangerOutlineFull: { alignItems: 'center', backgroundColor: '#0B0B12', borderColor: colors.red, borderRadius: 5, borderWidth: 1, justifyContent: 'center', marginTop: 12, minHeight: 44 },
  dangerOutlineText: { color: colors.red, fontSize: 13, fontWeight: '900', textTransform: 'uppercase' },
  smallButton: { alignItems: 'center', backgroundColor: '#0B0B12', borderColor: colors.blue, borderRadius: 5, borderWidth: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 12 },
  disabledButton: { borderColor: colors.line, opacity: 0.35 },
  smallButtonText: { color: colors.text, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  backButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#0B0B12', borderColor: colors.violet, borderRadius: 5, borderWidth: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 12 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 6, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 },
  chipActive: { backgroundColor: '#27272A', borderColor: colors.text },
  chipText: { color: colors.text, fontSize: 13, fontWeight: '900' },
  planHeader: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 16 },
  planMeta: { color: colors.yellow, fontSize: 30, fontWeight: '900' },
  card: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, padding: 14 },
  rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  cardTitle: { color: colors.text, fontSize: 20, fontWeight: '900' },
  textInput: { borderColor: colors.line, borderRadius: 5, borderWidth: 1, color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 6, minHeight: 44, paddingHorizontal: 10 },
  compactText: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 12 },
  exerciseList: { gap: 8, marginTop: 14 },
  exerciseBlock: { gap: 8 },
  exerciseRow: { alignItems: 'center', backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 6, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 64, padding: 10 },
  exerciseSelectArea: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 10, minWidth: 0 },
  exerciseActive: { borderColor: colors.yellow },
  exerciseNumber: { alignItems: 'center', backgroundColor: '#080810', borderRadius: 4, height: 34, justifyContent: 'center', width: 34 },
  exerciseNumberText: { color: colors.blue, fontWeight: '900' },
  exerciseBody: { flex: 1 },
  rowTitle: { color: colors.text, fontSize: 15, fontWeight: '900' },
  rowMuted: { color: colors.muted, fontSize: 12, marginTop: 3 },
  rowValue: { color: colors.blue, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  planEditor: { backgroundColor: '#0B0B12', borderColor: colors.line, borderRadius: 6, borderWidth: 1, gap: 8, padding: 8 },
  stepperRow: { flexDirection: 'row', gap: 8 },
  editorActions: { flexDirection: 'row', gap: 8 },
  reorderButton: { alignItems: 'center', borderColor: '#3F3F46', borderRadius: 5, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  reorderText: { color: colors.text, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  removeButton: { alignItems: 'center', borderColor: '#3F3F46', borderRadius: 5, borderWidth: 1, flex: 1.2, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  removeButtonText: { color: colors.muted, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  dragHandle: { alignItems: 'center', borderColor: colors.line, borderRadius: 5, borderWidth: 1, height: 34, justifyContent: 'center', width: 34 },
  dragHandleText: { color: colors.muted, fontSize: 15, fontWeight: '900' },
  iconRemoveButton: { alignItems: 'center', borderColor: colors.line, borderRadius: 5, borderWidth: 1, height: 34, justifyContent: 'center', width: 34 },
  iconRemoveText: { color: colors.red, fontSize: 16, fontWeight: '900' },
  stepper: { flex: 1, gap: 5, minWidth: 0 },
  stepperLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  stepperControls: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 5, borderWidth: 1, flexDirection: 'row', minHeight: 42, overflow: 'hidden' },
  readonlyMetric: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 5, borderWidth: 1, justifyContent: 'center', minHeight: 42 },
  stepperButton: { alignItems: 'center', alignSelf: 'stretch', justifyContent: 'center', width: 34 },
  stepperButtonText: { color: colors.blue, fontSize: 18, fontWeight: '900' },
  stepperValue: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '900', textAlign: 'center' },
  libraryDetailCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, gap: 12, padding: 14 },
  libraryHeroTop: { flexDirection: 'row', gap: 12 },
  metaPillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 },
  metaPill: { backgroundColor: '#0B0B12', borderColor: colors.line, borderRadius: 5, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 6 },
  metaPillText: { color: colors.muted, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  libraryList: { gap: 8 },
  libraryRow: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 6, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 54, padding: 12 },
  libraryRowActive: { borderColor: colors.yellow },
  exerciseDetailTitle: { flex: 1, gap: 4 },
  descriptionBox: { backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 6, borderWidth: 1, marginTop: 14, padding: 14 },
  descriptionHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  descriptionLabel: { color: colors.muted, fontSize: 11, fontWeight: '900', textTransform: 'uppercase' },
  descriptionText: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 8 },
  noteInput: { borderColor: colors.line, borderRadius: 6, borderWidth: 1, color: colors.text, fontSize: 14, lineHeight: 20, marginTop: 12, minHeight: 74, padding: 10, textAlignVertical: 'top' },
  workoutTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  timerCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, padding: 18 },
  timerCircle: { alignItems: 'center', borderColor: colors.text, borderRadius: 150, borderWidth: 3, height: 260, justifyContent: 'center', marginVertical: 18, width: 260 },
  timerMain: { color: colors.text, fontSize: 44, fontWeight: '500' },
  timerOvertime: { color: colors.red },
  timerSub: { color: colors.muted, fontSize: 16, marginTop: 6 },
  toggle: { backgroundColor: '#0B0B12', borderColor: colors.line, borderRadius: 6, borderWidth: 1, flexDirection: 'row', gap: 5, padding: 4 },
  toggleItem: { alignItems: 'center', borderRadius: 4, flex: 1, minHeight: 34, justifyContent: 'center', paddingHorizontal: 10 },
  toggleActive: { backgroundColor: colors.text },
  toggleText: { color: colors.muted, fontSize: 12, fontWeight: '900' },
  toggleTextActive: { color: '#030308', fontSize: 12, fontWeight: '900' },
  calendarMonth: { color: colors.text, fontSize: 26, fontWeight: '900' },
  calendarHint: { color: colors.muted, flex: 1, fontSize: 12, lineHeight: 16, textAlign: 'right' },
  weekHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  weekHeaderCenter: { alignItems: 'center', flex: 1 },
  iconButton: { alignItems: 'center', borderColor: colors.line, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  iconButtonText: { color: colors.text, fontSize: 28, fontWeight: '600', lineHeight: 30 },
  weekSchedule: { flexDirection: 'row' },
  weekDayCard: { backgroundColor: '#050507', borderBottomColor: colors.line, borderBottomWidth: 1, borderLeftColor: colors.line, borderLeftWidth: 1, borderTopColor: colors.line, borderTopWidth: 1, flex: 1, minHeight: 108, padding: 7 },
  weekDayFirst: { borderBottomLeftRadius: 8, borderTopLeftRadius: 8 },
  weekDayLast: { borderBottomRightRadius: 8, borderRightColor: colors.line, borderRightWidth: 1, borderTopRightRadius: 8 },
  calendarToday: { borderColor: colors.text, borderRadius: 8, borderWidth: 2 },
  calendarSelected: { backgroundColor: '#18181B', borderColor: colors.yellow, borderRadius: 8, borderWidth: 1 },
  calendarWeekday: { color: colors.muted, fontSize: 10, fontWeight: '900', textTransform: 'uppercase' },
  calendarNumber: { color: colors.text, fontSize: 15, fontWeight: '900' },
  calendarPlan: { color: colors.muted, fontSize: 9, fontWeight: '900', marginTop: 8 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '900', textTransform: 'uppercase' },
  profileCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, flexDirection: 'row', gap: 14, padding: 14 },
  profileLogo: { borderRadius: 6, height: 82, width: 82 },
  historyLogCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, padding: 14 },
  tabBar: { backgroundColor: '#080810', borderColor: colors.line, borderRadius: 8, borderWidth: 1, bottom: 18, flexDirection: 'row', gap: 5, left: 16, padding: 6, position: 'absolute', right: 16 },
  tabButton: { alignItems: 'center', borderRadius: 5, flex: 1, minHeight: 42, justifyContent: 'center' },
  tabActive: { backgroundColor: '#27272A' },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  tabTextActive: { color: colors.text },
});
