import { Platform, StyleSheet } from 'react-native';

export const colors = {
  ink: '#10131B',
  panel: '#191E2A',
  panelAlt: '#222A38',
  surface: '#121722',
  line: '#303849',
  text: '#F4F6FA',
  muted: '#9CA6B8',
  pink: '#ED849D',
  primary: '#340055',
  onPrimary: '#FFFFFF',
  // Neutral emphasis stays readable on dark surfaces; brand fills use primary.
  accent: '#F4F6FA',
  yellow: '#DEC183',
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: colors.ink },
  app: { flex: 1, backgroundColor: colors.ink, ...(Platform.OS === 'web' ? { width: '100%', maxWidth: 720, alignSelf: 'center' as const, minHeight: 0 } : {}) },
  background: { bottom: 0, left: 0, overflow: 'hidden', position: 'absolute', right: 0, top: 0 },
  bgLineOne: { backgroundColor: colors.primary, height: 860, left: 34, opacity: 0.015, position: 'absolute', top: -150, transform: [{ rotate: '22deg' }], width: 2 },
  bgLineTwo: { backgroundColor: colors.primary, height: 720, opacity: 0.015, position: 'absolute', right: 78, top: 20, transform: [{ rotate: '-18deg' }], width: 2 },
  bgLineThree: { backgroundColor: colors.primary, height: 560, opacity: 0.015, position: 'absolute', right: 18, top: 230, transform: [{ rotate: '38deg' }], width: 2 },
  header: { alignItems: 'center', flexDirection: 'row', gap: 10, paddingHorizontal: 18, paddingTop: 12, paddingBottom: 6 },
  logoFrame: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, height: 36, overflow: 'hidden', width: 36 },
  logo: { height: '100%', width: '100%' },
  headerText: { flex: 1 },
  title: { color: colors.text, fontSize: 22, fontWeight: '700', lineHeight: 28 },
  badge: { alignItems: 'center', backgroundColor: 'transparent', minWidth: 54, paddingVertical: 7 },
  badgeValue: { color: colors.yellow, fontSize: 20, fontWeight: '600' },
  badgeLabel: { color: colors.muted, fontSize: 10, fontWeight: '500' },
  headerClock: { alignItems: 'flex-end', justifyContent: 'center', minWidth: 64, paddingHorizontal: 6, paddingVertical: 2 },
  headerClockText: { color: colors.text, fontSize: 18, fontWeight: '600', fontVariant: ['tabular-nums'] },
  content: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 106 },
  workoutContent: { paddingBottom: 28 },
  savingStatus: { paddingHorizontal: 18, paddingBottom: 4, gap: 6 },
  savingStatusRow: { flexDirection: 'row', alignItems: 'center', gap: 6, minHeight: 18 },
  savingStatusText: { color: colors.muted, fontSize: 11, lineHeight: 16, flex: 1 },
  statusDot: { height: 5, width: 5, borderRadius: 3 },
  feedback: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 4, backgroundColor: colors.panelAlt, borderColor: colors.line, borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, marginBottom: 12 },
  feedbackText: { color: colors.text, fontSize: 12, lineHeight: 18, flex: 1, minWidth: 100, paddingVertical: 10 },
  feedbackAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 },
  feedbackActionText: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  feedbackClose: { minHeight: 44, minWidth: 36, alignItems: 'center', justifyContent: 'center' },
  feedbackCloseText: { color: colors.muted, fontSize: 22 },
  screen: { gap: 14 },
  hero: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 16, borderWidth: 1, overflow: 'hidden', padding: 18, position: 'relative' },
  heroGlow: { backgroundColor: colors.primary, height: 150, opacity: 0.03, position: 'absolute', right: -45, top: -45, transform: [{ rotate: '-22deg' }], width: 220 },
  eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '500', letterSpacing: 0.2 },
  heroTitle: { color: colors.text, fontSize: 34, fontWeight: '700', lineHeight: 40, marginTop: 4 },
  heroSub: { color: colors.muted, fontSize: 15, marginTop: 2 },
  quickStats: { flexDirection: 'row', gap: 8, marginTop: 16 },
  stat: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flex: 1, minHeight: 58, justifyContent: 'center', paddingHorizontal: 9 },
  statValue: { color: colors.text, fontSize: 17, fontWeight: '600' },
  statLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', marginTop: 2, textTransform: 'none' },
  primaryWide: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 10, justifyContent: 'center', marginTop: 14, minHeight: 48, paddingHorizontal: 14 },
  resumeWide: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 10, justifyContent: 'center', marginTop: 16, minHeight: 50 },
  primaryText: { color: colors.onPrimary, fontSize: 14, fontWeight: '700', textAlign: 'center' },
  secondaryFull: { alignItems: 'center', backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 10, borderWidth: 1, justifyContent: 'center', marginTop: 10, minHeight: 44, paddingHorizontal: 14, paddingVertical: 8 },
  secondaryText: { color: colors.text, fontSize: 14, fontWeight: '500', textAlign: 'center' },
  dangerOutlineFull: { alignItems: 'center', backgroundColor: 'transparent', borderColor: colors.line, borderRadius: 10, borderWidth: 1, justifyContent: 'center', marginTop: 10, minHeight: 44, paddingHorizontal: 12 },
  dangerOutlineText: { color: colors.pink, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  smallButton: { alignItems: 'center', backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 9, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 12 },
  disabledButton: { borderColor: colors.line, opacity: 0.35 },
  smallButtonText: { color: colors.text, fontSize: 12, fontWeight: '500', textAlign: 'center' },
  backButton: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: 'transparent', borderRadius: 9, justifyContent: 'center', minHeight: 44, paddingHorizontal: 10 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10 },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.text, fontSize: 13, fontWeight: '600' },
  card: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  rowBetween: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  cardTitle: { color: colors.text, fontSize: 20, fontWeight: '600' },
  textInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 16, fontWeight: '400', marginTop: 6, minHeight: 44, paddingHorizontal: 12, paddingVertical: 10 },
  compactText: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 12 },
  exerciseList: { gap: 8, marginTop: 14 },
  exerciseBlock: { gap: 8 },
  exerciseRow: { alignItems: 'center', backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 64, padding: 10 },
  exerciseNumber: { alignItems: 'center', backgroundColor: colors.panelAlt, borderRadius: 8, height: 34, justifyContent: 'center', width: 34 },
  exerciseNumberText: { color: colors.muted, fontWeight: '600' },
  exerciseBody: { flex: 1 },
  rowTitle: { color: colors.text, fontSize: 15, fontWeight: '600' },
  rowMuted: { color: colors.muted, fontSize: 12, marginTop: 3 },
  rowValue: { color: colors.accent, fontSize: 12, fontWeight: '500' },
  planEditor: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, gap: 8, padding: 8 },
  stepperRow: { flexDirection: 'row', gap: 8 },
  editorActions: { flexDirection: 'row', gap: 8 },
  templateActions: { flexDirection: 'row', gap: 10, marginTop: 12 },
  templateSecondaryAction: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 10 },
  templatePrimaryAction: { alignItems: 'center', backgroundColor: colors.primary, borderColor: colors.primary, borderRadius: 10, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 48, paddingHorizontal: 10 },
  quickStartList: { gap: 8, marginTop: 12 },
  quickStartRow: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 10, minHeight: 58, padding: 10 },
  quickStartButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 8, justifyContent: 'center', minHeight: 38, minWidth: 72, paddingHorizontal: 12 },
  quickStartButtonText: { color: colors.onPrimary, fontSize: 12, fontWeight: '600', textTransform: 'none' },
  planQuickCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  planQuickActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  planEditButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 42 },
  planStartButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 9, flex: 1.4, justifyContent: 'center', minHeight: 44 },
  reorderButton: { alignItems: 'center', borderColor: colors.line, borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  reorderText: { color: colors.text, fontSize: 11, fontWeight: '600', textTransform: 'none' },
  removeButton: { alignItems: 'center', borderColor: colors.pink, borderRadius: 8, borderWidth: 1, flex: 1.2, justifyContent: 'center', minHeight: 36, paddingHorizontal: 10 },
  removeButtonText: { color: colors.muted, fontSize: 11, fontWeight: '600', textTransform: 'none' },
  stepper: { flex: 1, gap: 5, minWidth: 0 },
  stepperLabel: { color: colors.muted, fontSize: 10, fontWeight: '600', textTransform: 'none' },
  stepperControls: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, flexDirection: 'row', minHeight: 42, overflow: 'hidden' },
  stepperButton: { alignItems: 'center', alignSelf: 'stretch', justifyContent: 'center', width: 34 },
  stepperButtonText: { color: colors.text, fontSize: 18, fontWeight: '500' },
  stepperValue: { color: colors.text, flex: 1, fontSize: 15, fontWeight: '600', textAlign: 'center' },
  libraryDetailCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, gap: 12, padding: 14 },
  libraryHeroTop: { flexDirection: 'row', gap: 12 },
  metaPillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 },
  metaPill: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 999, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 6 },
  metaPillText: { color: colors.accent, fontSize: 11, fontWeight: '600', textTransform: 'none' },
  libraryList: { gap: 8 },
  progressChartCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, padding: 14 },
  progressBars: { alignItems: 'flex-end', flexDirection: 'row', gap: 4, height: 104, marginVertical: 14 },
  progressBarColumn: { flex: 1, height: 96, justifyContent: 'flex-end' },
  progressBar: { borderRadius: 4, minHeight: 4, width: '100%' },
  progressBarPink: { backgroundColor: colors.pink },
  progressBarMint: { backgroundColor: colors.accent },
  progressBarYellow: { backgroundColor: colors.yellow },
  progressHistoryList: { gap: 4, marginTop: 10 },
  progressHistoryRow: { alignItems: 'center', borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10 },
  libraryRow: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 54, padding: 12 },
  libraryRowActive: { backgroundColor: colors.primary, borderColor: colors.primary, borderWidth: 1 },
  exerciseDetailTitle: { flex: 1, gap: 4 },
  descriptionBox: { backgroundColor: colors.panelAlt, borderColor: colors.line, borderRadius: 10, borderWidth: 1, marginTop: 12, padding: 12 },
  descriptionHeader: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  descriptionLabel: { color: colors.muted, fontSize: 11, fontWeight: '600', textTransform: 'none' },
  descriptionText: { color: colors.text, fontSize: 15, lineHeight: 22, marginTop: 8 },
  noteInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 14, lineHeight: 20, marginTop: 12, minHeight: 74, padding: 10, textAlignVertical: 'top' },
  workoutSetTypeRow: { marginBottom: 14, marginTop: 8 },
  workoutRestActions: { marginTop: 14 },
  workoutNoteLabel: { marginTop: 14 },
  workoutTop: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  compactWorkoutHeader: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 14 },
  restEditingHint: { alignItems: 'center', backgroundColor: colors.primary, borderColor: colors.line, borderRadius: 9, borderWidth: 1, minHeight: 38, justifyContent: 'center', paddingHorizontal: 10 },
  restEditingHintText: { color: colors.accent, fontSize: 12, fontWeight: '500' },
  setTableCard: { backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, overflow: 'hidden' },
  setTableHeader: { alignItems: 'center', backgroundColor: colors.surface, borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', minHeight: 36, paddingHorizontal: 8 },
  setHeaderText: { color: colors.muted, fontSize: 9, fontWeight: '600', textAlign: 'center', textTransform: 'none' },
  setTableRow: { alignItems: 'center', borderBottomColor: colors.line, borderBottomWidth: 1, flexDirection: 'row', minHeight: 58, paddingHorizontal: 8 },
  setTableRowActive: { backgroundColor: colors.primary, borderLeftColor: colors.accent, borderLeftWidth: 2 },
  setNumberCell: { alignItems: 'center', justifyContent: 'center', width: 38 },
  setPreviousCell: { flex: 1.15, minWidth: 0 },
  setMetricCell: { alignItems: 'center', flex: 1, justifyContent: 'center', minWidth: 0, paddingHorizontal: 3 },
  setDoneCell: { alignItems: 'center', justifyContent: 'center', width: 48 },
  setNumberText: { color: colors.text, fontSize: 14, fontWeight: '600' },
  setPreviousText: { color: colors.muted, fontSize: 12, fontWeight: '800', textAlign: 'center' },
  setMetricInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 8, borderWidth: 1, color: colors.text, fontSize: 16, fontWeight: '500', minHeight: 44, paddingHorizontal: 4, paddingVertical: 8, textAlign: 'center', width: '100%' },
  setDoneButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: 9, height: 44, justifyContent: 'center', width: 44 },
  setDoneButtonText: { color: colors.muted, fontSize: 18, fontWeight: '600' },
  setDoneComplete: { alignItems: 'center', backgroundColor: colors.primary, borderColor: colors.primary, borderWidth: 1, borderRadius: 9, height: 44, justifyContent: 'center', width: 44 },
  setDoneCompleteText: { color: colors.accent, fontSize: 17, fontWeight: '600' },
  setDonePending: { borderColor: colors.line, borderRadius: 9, borderWidth: 1, height: 44, width: 44 },
  addSetInline: { alignItems: 'center', justifyContent: 'center', minHeight: 44 },
  addSetInlineText: { color: colors.accent, fontSize: 12, fontWeight: '600', textTransform: 'none' },
  moreButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, justifyContent: 'center', minHeight: 44 },
  compactNoteInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 9, borderWidth: 1, color: colors.text, fontSize: 13, marginTop: 10, minHeight: 48, padding: 10, textAlignVertical: 'top' },
  timerCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 14, borderWidth: 1, padding: 18 },
  timerCircle: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.accent, borderRadius: 150, borderWidth: 4, elevation: 5, height: 260, justifyContent: 'center', marginVertical: 18, shadowColor: colors.accent, shadowOffset: { height: 0, width: 0 }, shadowOpacity: 0.2, shadowRadius: 14, width: 260 },
  timerMain: { color: colors.yellow, fontSize: 44, fontWeight: '700' },
  timerOvertime: { color: colors.pink },
  timerSub: { color: colors.muted, fontSize: 16, marginTop: 6 },
  contentWithRestDock: { paddingBottom: 124 },
  restDock: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 14, borderWidth: 1, bottom: 12, elevation: 8, flexDirection: 'row', gap: 8, left: 12, minHeight: 72, padding: 10, position: 'absolute', right: 12, shadowColor: '#000', shadowOffset: { height: 4, width: 0 }, shadowOpacity: 0.18, shadowRadius: 12 },
  restDockTimer: { alignItems: 'center', borderRightColor: colors.line, borderRightWidth: 1, justifyContent: 'center', minWidth: 64, paddingRight: 10 },
  restDockLabel: { color: colors.accent, fontSize: 9, fontWeight: '600', textTransform: 'none' },
  restDockTime: { color: colors.text, fontSize: 23, fontWeight: '600', fontVariant: ['tabular-nums'], marginTop: 2 },
  restDockActions: { flex: 1, flexDirection: 'row', gap: 6 },
  restDockButton: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 8, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 44 },
  restDockButtonText: { color: colors.text, fontSize: 11, fontWeight: '600' },
  restDockSkip: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 8, flex: 1.15, justifyContent: 'center', minHeight: 44 },
  restDockSkipText: { color: colors.onPrimary, fontSize: 11, fontWeight: '600', textTransform: 'none' },
  toggle: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 10, borderWidth: 1, flexDirection: 'row', gap: 5, padding: 4 },
  toggleItem: { alignItems: 'center', borderRadius: 4, flex: 1, minHeight: 34, justifyContent: 'center', paddingHorizontal: 10 },
  toggleActive: { backgroundColor: colors.primary },
  toggleText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  toggleTextActive: { color: colors.accent, fontSize: 12, fontWeight: '600' },
  calendarMonth: { color: colors.text, fontSize: 24, fontWeight: '600' },
  calendarHint: { color: colors.muted, flex: 1, fontSize: 12, lineHeight: 16, textAlign: 'right' },
  weekHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  weekHeaderCenter: { alignItems: 'center', flex: 1 },
  iconButton: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  iconButtonText: { color: colors.accent, fontSize: 28, fontWeight: '600', lineHeight: 30 },
  weekSchedule: { flexDirection: 'row' },
  weekDayCard: { backgroundColor: colors.surface, borderBottomColor: colors.line, borderBottomWidth: 1, borderLeftColor: colors.line, borderLeftWidth: 1, borderTopColor: colors.line, borderTopWidth: 1, flex: 1, minHeight: 96, padding: 7 },
  weekDayFirst: { borderBottomLeftRadius: 8, borderTopLeftRadius: 8 },
  weekDayLast: { borderBottomRightRadius: 8, borderRightColor: colors.line, borderRightWidth: 1, borderTopRightRadius: 8 },
  calendarToday: { borderColor: colors.accent, borderRadius: 10, borderWidth: 1 },
  calendarSelected: { backgroundColor: colors.primary, borderColor: colors.primary, borderRadius: 10, borderWidth: 1 },
  calendarWeekday: { color: colors.muted, fontSize: 10, fontWeight: '600', textTransform: 'none' },
  calendarNumber: { color: colors.text, fontSize: 15, fontWeight: '600' },
  calendarWorkoutDone: { color: colors.accent, fontSize: 13, fontWeight: '600', marginTop: 10 },
  calendarWorkoutEmpty: { color: colors.line, fontSize: 13, fontWeight: '600', marginTop: 10 },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '600' },
  profileCard: { alignItems: 'center', backgroundColor: colors.panel, borderColor: colors.line, borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 14, padding: 14 },
  profileLogo: { borderRadius: 6, height: 82, width: 82 },
  historyLogCard: { backgroundColor: colors.panel, borderColor: colors.line, borderLeftColor: colors.primary, borderLeftWidth: 3, borderRadius: 12, borderWidth: 1, padding: 14 },
  tabBar: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: 14, borderWidth: 1, bottom: 14, elevation: 8, flexDirection: 'row', gap: 4, left: 14, padding: 5, position: 'absolute', right: 14, shadowColor: '#000', shadowOffset: { height: 4, width: 0 }, shadowOpacity: 0.18, shadowRadius: 12 },
  tabButton: { alignItems: 'center', borderRadius: 10, flex: 1, minHeight: 42, justifyContent: 'center' },
  tabActive: { backgroundColor: colors.primary },
  tabText: { color: colors.muted, fontSize: 11, fontWeight: '500' },
  tabTextActive: { color: colors.onPrimary },
});
